name: Postgres Service

on:
  push:
    branches:
      - main

jobs:
  postgres-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
        options: >-
          --health-cmd="pg_isready -U myuser -d mydb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          while ! nc -z localhost 5432; do
            sleep 1
          done
          echo "Postgres is ready!"

      - name: Test Postgres connection
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          PGPASSWORD=mypassword psql -h localhost -U myuser -d mydb -c "SELECT version();"
