name: Run Automated Tests
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=. --cov-report=term-missing
      # run: pytest -x --cov=. --cov-report=term-missing (stops the workflow after the first failure)


          
